"""
Phase 21 Operational Alert Model.

Stores deterministic operational alerts with standard lifecycle management
(OPEN, ACKNOWLEDGED, RESOLVED, SUPPRESSED).
"""

import uuid
from datetime import datetime, timezone
from sqlalchemy import (
    Column,
    String,
    DateTime,
    Text,
    JSON,
    ForeignKey,
    Index,
)
from app.core.database import Base


def utc_now() -> datetime:
    return datetime.now(timezone.utc)


def generate_alert_id() -> str:
    return f"alert-{uuid.uuid4().hex}"


class OperationalAlert(Base):
    """
    Durable alert entity generated by deterministic alert evaluation rules.
    """
    __tablename__ = "operational_alerts"

    id = Column(String(64), primary_key=True, default=generate_alert_id, index=True)
    workspace_id = Column(
        String(36),
        ForeignKey("workspaces.id", ondelete="CASCADE"),
        nullable=False,
        default="ws-default",
        index=True,
    )
    alert_name = Column(String(128), nullable=False, index=True)
    alert_type = Column(String(64), nullable=False, index=True)
    severity = Column(String(32), nullable=False, default="WARNING", index=True)
    status = Column(String(32), nullable=False, default="OPEN", index=True)
    summary = Column(Text, nullable=False)
    details = Column(JSON, nullable=True)
    fingerprint = Column(String(128), nullable=False, index=True)
    trace_id = Column(String(64), nullable=True, index=True)
    acknowledged_by = Column(String(128), nullable=True)
    acknowledged_at = Column(DateTime(timezone=True), nullable=True)
    resolved_at = Column(DateTime(timezone=True), nullable=True)
    created_at = Column(DateTime(timezone=True), default=utc_now, nullable=False, index=True)
    updated_at = Column(DateTime(timezone=True), default=utc_now, onupdate=utc_now, nullable=False)

    __table_args__ = (
        Index("ix_op_alerts_ws_status", "workspace_id", "status"),
        Index("ix_op_alerts_ws_fingerprint", "workspace_id", "fingerprint"),
    )
