"""
Phase 20 Deterministic LLM Validation Service.

Ensures that all structured proposals generated by an LLM strictly satisfy
application-level invariants, schema constraints, confidence bounds, entity
existence, and security rules before touching domain state.
"""

import re
from typing import Optional, List, Dict, Any, Tuple
from app.core.status_machine import ObligationType
from app.schemas.llm import (
    ObligationProposal,
    EventSemanticProposal,
    EvidenceInterpretationProposal,
    LLMValidationStatus,
)


class LLMValidationService:
    """
    Deterministic validator for LLM structured outputs.
    Never silently repairs fabricated facts; rejects or flags for human review.
    """

    ADVERSARIAL_PATTERNS = [
        r"ignore\s+previous\s+instructions",
        r"system\s+prompt",
        r"delete\s+from",
        r"drop\s+table",
        r"<script>",
        r"grant\s+all\s+privileges",
        r"override\s+security",
    ]

    @classmethod
    def validate_obligation_proposal(
        cls,
        proposal: ObligationProposal,
        known_users: Optional[List[str]] = None,
        workspace_id: Optional[str] = None,
    ) -> Tuple[LLMValidationStatus, List[str]]:
        errors: List[str] = []

        # 1. Action content check
        if not proposal.action or len(proposal.action.strip()) < 3:
            errors.append("Action is missing or too short to represent a viable obligation.")

        # 2. Confidence bounds check
        if not (0.0 <= proposal.confidence <= 1.0):
            return LLMValidationStatus.CONFIDENCE_OUT_OF_BOUNDS, [
                f"Confidence score {proposal.confidence} is outside valid [0.0, 1.0] bounds."
            ]

        # 3. Adversarial / Prompt Injection containment check
        for pattern in cls.ADVERSARIAL_PATTERNS:
            if re.search(pattern, proposal.action, re.IGNORECASE) or (
                proposal.reasoning and re.search(pattern, proposal.reasoning, re.IGNORECASE)
            ):
                return LLMValidationStatus.SECURITY_REJECTED, [
                    f"Adversarial or prompt injection instruction detected: '{pattern}'"
                ]

        # 4. Valid Obligation Type check
        valid_types = {t.value for t in ObligationType} | {"OWED_TO_ME", "OWED_BY_ME", "MUTUAL"}
        if proposal.obligation_type not in valid_types:
            errors.append(f"Invalid obligation_type '{proposal.obligation_type}'. Must be one of {valid_types}.")

        # 5. Known identity validation (if workspace member roster provided)
        if known_users and proposal.owner:
            norm_known = {u.strip().lower() for u in known_users}
            if proposal.owner.strip().lower() not in norm_known:
                # Flag as unknown entity for human review
                return LLMValidationStatus.UNKNOWN_ENTITY, [
                    f"Owner '{proposal.owner}' is not a recognized member of workspace '{workspace_id or 'default'}'."
                ]

        # 6. Schema version verification
        if not proposal.schema_version or not proposal.schema_version.startswith("obligation-proposal"):
            errors.append(f"Unrecognized schema_version '{proposal.schema_version}'.")

        if errors:
            return LLMValidationStatus.INVALID_SCHEMA, errors

        return LLMValidationStatus.VALID, []

    @classmethod
    def validate_event_semantics(
        cls,
        proposal: EventSemanticProposal,
    ) -> Tuple[LLMValidationStatus, List[str]]:
        errors: List[str] = []

        valid_roles = {
            "COMPLETION_SIGNAL",
            "COMMITMENT",
            "REQUEST",
            "PROGRESS_UPDATE",
            "NEGATIVE_BLOCKER",
            "IRRELEVANT",
        }
        if proposal.semantic_role not in valid_roles:
            errors.append(f"Invalid semantic_role '{proposal.semantic_role}'. Must be one of {valid_roles}.")

        if not (0.0 <= proposal.confidence <= 1.0):
            return LLMValidationStatus.CONFIDENCE_OUT_OF_BOUNDS, [
                f"Confidence {proposal.confidence} is out of bounds."
            ]

        if errors:
            return LLMValidationStatus.INVALID_SCHEMA, errors

        return LLMValidationStatus.VALID, []

    @classmethod
    def validate_evidence_interpretation(
        cls,
        proposal: EvidenceInterpretationProposal,
    ) -> Tuple[LLMValidationStatus, List[str]]:
        errors: List[str] = []
        valid_cats = {"COMPLETION", "PROGRESS", "REQUEST", "COMMITMENT", "NEGATIVE_BLOCKER", "AMBIGUOUS"}
        if proposal.evidence_category not in valid_cats:
            errors.append(f"Invalid evidence_category '{proposal.evidence_category}'.")

        if not (0.0 <= proposal.confidence <= 1.0):
            return LLMValidationStatus.CONFIDENCE_OUT_OF_BOUNDS, ["Confidence out of bounds."]

        if errors:
            return LLMValidationStatus.INVALID_SCHEMA, errors

        return LLMValidationStatus.VALID, []
